<?php

declare(strict_types=1);

namespace App\Domain\Identity\Token\ValueObject;

use InvalidArgumentException;
use Stringable;

/**
 * Immutable identity for a refresh token record. A ULID (time-ordered) matching the platform
 * id contract (unero-shared-schemas common.schema.json #/$defs/Ulid). Generated by the
 * repository's nextIdentity(); never reassigned. Distinct from the opaque token secret the
 * client holds — this id keys the row, the secret is only ever stored as a SHA-256 hash.
 */
final readonly class RefreshTokenId implements Stringable
{
    private const string PATTERN = '/^[0-7][0-9A-HJKMNP-TV-Z]{25}$/';

    public function __construct(public string $value)
    {
        if (preg_match(self::PATTERN, $value) !== 1) {
            throw new InvalidArgumentException("Invalid RefreshTokenId (expected ULID): {$value}");
        }
    }

    public static function fromString(string $value): self
    {
        return new self($value);
    }

    public function equals(self $other): bool
    {
        return $this->value === $other->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}
